name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/build-push-action@v6
      name: Build and push
      with:
        push: true
        tags: marijndoeve/proxmox-qdevice:latest

      
